project_name: spv-wallet-web-backend
env:
  - DOCKERHUB_USERNAME={{ if index .Env "DOCKERHUB_USERNAME"  }}{{ .Env.DOCKERHUB_USERNAME }}{{ else }}4chainstudio{{ end }}
  - DOCKERHUB_REPONAME={{ if index .Env "DOCKERHUB_REPONAME"  }}{{ .Env.DOCKERHUB_REPONAME }}{{ else }}{{ .ProjectName }}{{ end }}
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-build
    main: ./cmd/main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - '8'
    env:
      - CC_linux_arm64={{ if index .Env "CC_linux_arm64"  }}{{.Env.CC_linux_arm64}}{{ else }}aarch64-linux-gnu-gcc{{ end }}
      - CC_linux_amd64={{ if index .Env "CC_linux_amd64"  }}{{.Env.CC_linux_amd64}}{{ else }}gcc{{ end }}
      - 'CC={{ index .Env (print "CC_" .Os "_" .Arch) }}'

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ title .Os }}_{{ replace .Arch "amd64" "x86_64"  }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - data/sql/migrations

checksum:
  extra_files:
    - glob: release/artifacts/darwin/*

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - '{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:latest-amd64'
      - '{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:{{ .Version }}-amd64'
      - '{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:{{ .Version }}-{{ .ShortCommit }}-amd64'
      - '{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:{{ .Tag }}-amd64'
      - '{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:v{{ .Major }}-amd64'
      - '{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:v{{ .Major }}.{{ .Minor }}-amd64'
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{ .Env.SOURCE_URL }}"
      - "--platform=linux/amd64"
      - "--build-arg=project_name={{.ProjectName}}"
      - "--build-arg=version={{.Version}}"
    dockerfile: release/Dockerfile
    extra_files:
      - data/sql/migrations/
      - release/entrypoint.sh
  - goos: linux
    goarch: arm64
    image_templates:
      - '{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:latest-arm64'
      - '{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:{{ .Version }}-{{ .ShortCommit }}-arm64'
      - '{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:{{ .Tag }}-arm64'
      - '{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:v{{ .Major }}-arm64'
      - '{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:v{{ .Major }}.{{ .Minor }}-arm64'
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{ .Env.SOURCE_URL }}"
      - "--platform=linux/arm64/v8"
      - "--build-arg=project_name={{.ProjectName}}"
      - "--build-arg=version={{.Version}}"
    dockerfile: release/Dockerfile
    extra_files:
      - data/sql/migrations/
      - release/entrypoint.sh

docker_manifests:
  - name_template: "{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:latest"
    image_templates:
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:latest-amd64"
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:latest-arm64"
  - name_template: "{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:{{ .Version }}-{{ .ShortCommit }}"
    image_templates:
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:{{ .Version }}-{{ .ShortCommit }}-amd64"
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:{{ .Version }}-{{ .ShortCommit }}-arm64"
  - name_template: "{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:{{ .Tag }}"
    image_templates:
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:{{ .Tag }}-amd64"
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:{{ .Tag }}-arm64"
  - name_template: "{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:v{{ .Major }}"
    image_templates:
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:v{{ .Major }}-amd64"
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:v{{ .Major }}-arm64"
  - name_template: "{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:v{{ .Major }}.{{ .Minor }}-amd64"
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:v{{ .Major }}.{{ .Minor }}-arm64"

release:
  name_template: "Release v{{.Version}}"
  extra_files:
    - glob: release/artifacts/darwin/*
  footer: |
    ## Docker images

    `docker pull {{ .Env.DOCKERHUB_USERNAME }}/{{ .Env.DOCKERHUB_REPONAME }}:{{ .Tag }}`


snapshot:
  name_template: "{{ incminor .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^(build|chore|ci|docs|refactor|test){1}(\([\w\-\.]+\))?(!)?:'
